name: Sync Fork from Upstream

on:
  schedule:
    - cron: "0 */1 * * *"  # 每1小时同步一次
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史

      - name: Add upstream & fetch
        run: |
          git config --global user.name "oiwedsio"
          git config --global user.email "chenwuyanbo@gmail.com"
          git remote add upstream https://github.com/LunaTechLab/MoonTV
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main  
          git merge upstream/main
          git push origin main
